In [1]:
# Open notebook from D drive: jupyter notebook --notebook-dir=D:/

## 1. Python/numpy multiplication operators:

- If matrices defined by np.matrix, * would give matrix multiplication. Now all matrices defined as ndarray/numpy array, so * will do element wise. 

- np.matrix is deprecated.

- **@** is called infix operator for matrix multiplication in **python**. The matmul function implements the semantics of the @ operator introduced in Python 3.5 following PEP465. @ is same as np.matmul without method parameters.

- Using **a.dot(b)** or **np.matmul(a,b)** is better IMO. Both are numpy operators. I would prefer the second.


### > `a.dot(b):`
https://numpy.org/doc/stable/reference/generated/numpy.dot.html

**`numpy.dot(a, b, out=None)`**

Dot product of two arrays. Specifically,

1. If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

2. If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

3. If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

4. If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

5. If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

### > `numpy.matmul`
https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

numpy.matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj, axes, axis]) = <ufunc 'matmul'>
Matrix product of two arrays.

**Parameters**
x1, x2array_like
- Input arrays, scalars not allowed.

outndarray, optional
- A location into which the result is stored. If provided, it must have a shape that matches the signature (n,k),(k,m)->(n,m). If not provided or None, a freshly-allocated array is returned.

**kwargs**
For other keyword-only arguments, see the ufunc docs.
New in version 1.16: Now handles ufunc kwargs

**Returns**
yndarray
The matrix product of the inputs. This is a scalar only when both x1, x2 are 1-d vectors.

**Raises**
ValueError
- If the last dimension of x1 is not the same size as the second-to-last dimension of x2.
- If a scalar value is passed in.


**The behavior depends on the arguments in the following way.**

1. If both arguments are 2-D they are multiplied like conventional matrices.

2. If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.

3. If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.

4. If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.

**matmul differs from dot in two important ways:**

- Multiplication by scalars is not allowed, use * instead.

- Stacks of matrices are broadcast together as if the matrices were elements, respecting the signature (n,k),(k,m)->(n,m):broadcast together as if the matrices were elements, respecting the signature (n,k),(k,m)->(n,m):

In [28]:
import numpy as np

## Different combinations of vector and matrix multiplication:

### 1. Vector x Vector dot product

**Basic operations:**

In [29]:

a = np.array([2,3,4])
b = np.array([5,6,7])

a*b

array([10, 18, 28])

In [30]:
a@b

56

In [31]:
a.dot(b)

56

In [32]:
np.matmul(a,b)

56

Matmul has same results as dot product. Going to use dot product for this practice notebook. 

Also, taking transpose to convert vector dot product to vector multiplication is theoretic notation to understand how multiplication is done. Numpy functions undertand how to proceed, so no need to manually transpose while calling dot or matmul. Therefore, unless otherwise needed, like in the normal equation, don't take transpose, a.dot(b) or np.matmul(a,b) should take care of it.



**Commutative property:**

- For dot prdouct:

In [33]:
print("Is vector dot product commutative?  ", np.array_equal(a.dot(b), b.dot(a)))
print (a.dot(b))

Is vector dot product commutative?   True
56


- For transpose of vectors within dot product:

In [34]:
print("Is transpose in vector dot product commutative?  ", 
      np.array_equal(a.T.dot(b),a.dot(b.T)))

print(a.T.dot(b))

Is transpose in vector dot product commutative?   True
56


**Is regular vs transoposed (either one of the vectors or both) in vector multiplication equal:**


In [35]:
print("Is vector dot product with a.dot(b) and a.T.dot(b) equal?  ", 
      np.array_equal(a.T.dot(b),a.dot(b.T)))

print("Is vector dot product with b.dot(a) and b.T.dot(a) equal?  ", 
      np.array_equal(b.dot(a),b.dot(a.T)))

Is vector dot product with a.dot(b) and a.T.dot(b) equal?   True
Is vector dot product with b.dot(a) and b.T.dot(a) equal?   True


In [36]:
print("Is transposing both vector and taking dot product commutative?  ", 
      np.array_equal(a.T.dot(b.T),b.T.dot(a.T)))

print("Does transposing both vector and taking dot product give same result as a.dot(b)?  ", 
      np.array_equal(a.T.dot(b.T),a.dot(b)))

a.T.dot(b.T)

Is transposing both vector and taking dot product commutative?   True
Does transposing both vector and taking dot product give same result as a.dot(b)?   True


56

**Conclusion:** *Vector dot product is a scaler, so either way, a single number. Vector dot product has lot's of flexibility.*



### 2. Matrix x vector or vector x matrix:

Vector is just a 1D matrix. 

In [37]:
vector = np.array([2,3,4])
matrix = np.array([[5,6,7],[5,6,7],[5,6,7]])

print("shape of vector is: ", vector.shape)
print("shape of matrix is: ", matrix.shape)


shape of vector is:  (3,)
shape of matrix is:  (3, 3)


vector is a column vector, with 3 rows and 1 column,\
matrix is a 3x3 matrix

#### Basic operations:

- vector into matrix:

In [38]:
# By normal linear algebra, this should give an error, as number of columns of vector are 1,
# and number of rows of matrix is 3.However, dot does some padding to make both compatible by inserting 
# columns of 1s, and then discarding their result after multiplication

vector_into_matrix = vector.dot(matrix)
vector_into_matrix

array([45, 54, 63])

In [39]:
# Explanation:

vector_padded = np.array ([[1,1,1],[1,1,1], [2,3,4]])
vector_padded_into_matrix = vector_padded.dot(matrix)
vector_padded_into_matrix

# As you can see, the result we get is the last row only, and first two rows are discarded.

array([[15, 18, 21],
       [15, 18, 21],
       [45, 54, 63]])

- matrix into vector: 

In [40]:
# this one is obvious, as number of columns of matrix are equal to number of rows of vector. 
# This is also most common, multipying matrix by vector in linear algebra
matrix_into_vector = matrix.dot(vector)
matrix_into_vector

array([56, 56, 56])

#### Commutative property:

- For dot product:

In [41]:
# we've already seen it is not commutative

print("Is matrix-vector multiplication commutative?  ", np.array_equal(vector.dot(matrix), matrix.dot(vector)))
      
print ("\nvector.dot(matrix) is:\n", vector.dot(matrix), "\n\nmatrix.dot(vector) is:\n", matrix.dot(vector))

Is matrix-vector multiplication commutative?   False

vector.dot(matrix) is:
 [45 54 63] 

matrix.dot(vector) is:
 [56 56 56]


- for transpose

In [42]:
print("Is transpose in vector-matrix multiplication commutative?  ", np.array_equal(vector.dot(matrix.T), vector.T.dot(matrix)))
      
print ("\nvector.dot(matrix.T) is:\n", vector.dot(matrix.T), "\n\nvector.T.dot(matrix) is:\n", vector.T.dot(matrix))

Is transpose in vector-matrix multiplication commutative?   False

vector.dot(matrix.T) is:
 [56 56 56] 

vector.T.dot(matrix) is:
 [45 54 63]


In [43]:
print("Is transpose in matrix-vector multiplication commutative?  ", np.array_equal(matrix.dot(vector.T), matrix.T.dot(vector)))
      
print ("\nmatrix.dot(vector.T) is:\n",matrix.dot(vector.T), "\n\nmatrix.T.dot(vector) is:\n", matrix.T.dot(vector))

Is transpose in matrix-vector multiplication commutative?   False

matrix.dot(vector.T) is:
 [56 56 56] 

matrix.T.dot(vector) is:
 [45 54 63]


**Is regular vs transposed (either one of the vectors or both) in vector-matrix or matrix-vector multiplication equal?**

This is interesting. While the commutative property does not hold for dot product or transpose when order of multiplication is kept same, it holds when second element in multiplication is transposed, or order of multiplication is reveresed along with transpose:

`vector.dot(matrix) = vector.T.dot(matrix) = matrix.T.dot(vector) = [45 54 63] `\
`matrix.dot(vector) = matrix.dot(vector.T) = vector.dot(matrix.T)= [56 56 56] `

A little weird, but point is to follow equations and multiply accordingly, in correct order. 
for the sake of completeness, taking transpose of both vector and matrix and checking result:

In [44]:
print("Is transposing both matrices and multiplying commutative?  ", np.array_equal(vector.T.dot(matrix.T), matrix.T.dot(vector.T)))

print ("\nvector.T.dot(matrix.T) is:\n", vector.T.dot(matrix.T), "\n\nmatrix.T.dot(vector.T) is:\n", matrix.T.dot(vector.T))

Is transposing both matrices and multiplying commutative?   False

vector.T.dot(matrix.T) is:
 [56 56 56] 

matrix.T.dot(vector.T) is:
 [45 54 63]


**Conclusion:** *add checks in code to see if multiplication was done correctly.*


`vector.dot(matrix) = vector.T.dot(matrix) = matrix.T.dot(vector) = matrix.T.dot(vector.T) = [45 54 63] `
`matrix.dot(vector) = matrix.dot(vector.T) = vector.dot(matrix.T)= vector.T.dot(matrix.T) = [56 56 56] `

A vector and its transpose seem to be pretty much the same, probably due to dimensions being adjusted to facilitate multiplication. Not sure.

I would narrow it down as:

`vector.dot(matrix) = matrix.T.dot(vector) = [45 54 63] `
`matrix.dot(vector) = vector.dot(matrix.T) = [56 56 56] `



### 3. Matrix x Matrix Multiplication:

**Is matrix multiplication same as dot product?**

In short yes, each entry in the product matrix is the dot product of a row in the first matrix and a column in the second matrix.


#### Basic operations:

In [45]:
x= np.array([[2,3,4],[2,3,4],[2,3,4]])
y= np.array([[5,6,7],[5,6,7],[5,6,7]])

x*y

array([[10, 18, 28],
       [10, 18, 28],
       [10, 18, 28]])

In [46]:
x.dot(y)

array([[45, 54, 63],
       [45, 54, 63],
       [45, 54, 63]])

#### Commutative property:

- For dot product:

In [47]:
print("Is matrix multiplication commutative?  ", np.array_equal(x.dot(y), y.dot(x)))
      
print ("\nx.dot(y) is:\n", x.dot(y), "\n\ny.dot(x) is:\n", y.dot(x))

Is matrix multiplication commutative?   False

x.dot(y) is:
 [[45 54 63]
 [45 54 63]
 [45 54 63]] 

y.dot(x) is:
 [[36 54 72]
 [36 54 72]
 [36 54 72]]


- For transpose of vectors within dot product:

In [48]:
print("Is transpose in matrix multiplication commutative?  ", np.array_equal(x.T.dot(y), y.T.dot(x)))
      
print ("\nx.T.dot(y) is:\n", x.T.dot(y), "\n\ny.T.dot(x) is:\n", y.T.dot(x))

Is transpose in matrix multiplication commutative?   False

x.T.dot(y) is:
 [[30 36 42]
 [45 54 63]
 [60 72 84]] 

y.T.dot(x) is:
 [[30 45 60]
 [36 54 72]
 [42 63 84]]


**Is regular vs transposed (either one of the vectors or both) in vector multiplication equal?**

None of the transposed multiplication is equal to any of the x.dot(y) or y.dot(x): 

In [49]:
print (np.array_equal(x.dot(y), x.T.dot(y))) 

print (np.array_equal(y.dot(x), y.T.dot(x)))

False
False


Also, transposing both matrices is also completely different from each other or any of the calculations before.

In [50]:
print("Is transposing both matrices and multiplying commutative?  ", np.array_equal(x.T.dot(y.T), y.T.dot(x.T)))

print ("\nx.T.dot(y.T) is:\n", x.T.dot(y.T), "\n\ny.T.dot(x.T) is:\n", y.T.dot(x.T))

Is transposing both matrices and multiplying commutative?   False

x.T.dot(y.T) is:
 [[36 36 36]
 [54 54 54]
 [72 72 72]] 

y.T.dot(x.T) is:
 [[45 45 45]
 [54 54 54]
 [63 63 63]]


**Conclusion:** *Matrix multiplication has completely different rules from vector multiplication. Matrix multiplication strictly depends on order of multiplication, and taking transpose of either or both matrices changes the results completely.*

### 4. Normal Equation:

`X` = feature matrix
`w` = weights of the feature matrix
`y` = traget variable to be predicted

`X.w = y`
Now, to find w which are the weights, is general LA, we'd do:

`w =  inv(X).y`

However, since X is a matrix, and it could be a singular matrix (meaning it's determinant is zero, because  its rows are linearly dependent vectors, or its columns are linearly dependent vectors). On top of it, X has to be square to find determinant in the first place. So we multiply X with X.T in left hand order, to make sure we have a square matrix and creating a Gram matrix. Found this online: "The column Gram matrix (A.T.A) is not invertible only if columns of A are linearly dependent. Thus if columns of A are linearly independent then the Gram matrix is invertible."  Anyways, now we have a matrix we can possibly invert:


`(X.T.X).w = y
inv(X.T.X).(X.T.X).w = inv(X.T.X).X.T.y
I.w = inv(X.T.X).X.T.y
w = inv(X.T.X).X.T.y`


Overall euqation looks like this:

`inv(X.T.X).(X.T.X).w = inv(X.T.X).(X.T).y`